### ISSUE TITLE
USERS has no attribute 'check_password'

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#23]
After updating with the latest commit, I got this error when I tried to re-run a model import.  I re-ran bin/ms-config with my settings file just in case, and still got the same error.

Stack trace for event: Object class ModelSEED::ModelDB::USERS has no attribute 'check_password'.
    Tracer::Confess('Object class ModelSEED::ModelDB::USERS has no attribute \'che...') called at /Users/seaver/Software/ModelSEEDCore/lib/PPO/DBObject.pm line 735
    DBObject::AUTOLOAD('ModelSEED::ModelDB::USERS=HASH(0xe1a9e0)', 'bollocks') called at /Users/seaver/Software/ModelSEEDCore/lib/ModelSEED/FIGMODEL.pm line 809
    ModelSEED::FIGMODEL::authenticate('ModelSEED::FIGMODEL=HASH(0xdac400)', 'HASH(0xdac5e0)') called at /Users/seaver/Software/ModelSEEDCore/lib/ModelSEED/FIGMODEL.pm line 778
    ModelSEED::FIGMODEL::authenticate_user('ModelSEED::FIGMODEL=HASH(0xdac400)', 'seaver', 'bollocks') called at /Users/seaver/Software/ModelSEEDCore/lib/ModelSEED/FIGMODEL.pm line 122
    ModelSEED::FIGMODEL::new('ModelSEED::FIGMODEL') called at /Users/seaver/Software/ModelSEEDCore/lib/ModelSEED/ModelDriver.pm line 23
    ModelSEED::ModelDriver::new('ModelSEED::ModelDriver') called at /Users/seaver/Software/ModelSEEDCore/lib/ModelSEED/ModelDriver.pl line 26
    require /Users/seaver/Software/ModelSEEDCore/lib/ModelSEED/ModelDriver.pl called at /Users/seaver/Software/ModelSEEDCore/config//ModelSEEDbootstrap.pm line 23
    main::run() called at -e line 3
Object class ModelSEED::ModelDB::USERS has no attribute 'check_password'.
Failure running /Users/seaver/Software/ModelSEEDCore/lib/ModelSEED/ModelDriver.pl: >>> Object class ModelSEED::ModelDB::USERS has no attribute 'check_password'. at /Users/seaver/Software/ModelSEEDCore/lib/PPO/DBObject.pm line 735

**Comment by devoid** [comment]
Sorry, I accidentally the whole USER.pm file. It's fixed now.

**Comment by samseaver** [comment]
Problem still exists after I pulled the latest updates this morning

**Comment by samseaver** [comment]
I restored the USERS.pm personally, not sure why it disappeared, but its working now
